language: ruby
rvm:
- 2.4.1
script:
 - rubocop
install: gem install rubocop -v 0.52.1
notifications:
  irc:
    channels:
      - "irc.cahbot.pro#soarn.pro"
    template:
      - "Build #%{build_number}: %{message} Time Elapsed: %{elapsed_time}. %{build_url}"
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
    skip_join: true
    nick: saorn-you-failed

  webhooks:
    urls:
      - https://n.tkte.ch/h/5572/gzZnD80loltP7nsckuoVlGD7
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
